name: Cutty
options:
  bundleIdPrefix: com.luisnavarro
targets:
  Cutty:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Sources
    settings:
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
      PRODUCT_NAME: Cutty
      SWIFT_VERSION: 5.9
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      CODE_SIGNING_ALLOWED: NO
      CODE_SIGNING_REQUIRED: NO
      CODE_SIGN_IDENTITY: ""
